<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>$schema</key>
	<string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
	<key>name</key>
	<string>JASM</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numerics</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#identifiers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#line_comment</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>identifiers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.jasm</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([a-zA-Z][a-zA-Z0-9]+):</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(r#)?\b(create|store|load|unload|jump|jumpTrue|jumpFalse|jumpTruePop|jumpFalsePop|jumpNil|bodyMarker|makeFunc|blkA|blkR|call|memberCall|attr|return|pushLoop|popLoop|continue|break|pushJump|pushJumpName|popJump)\b</string>
					<key>name</key>
					<string>keyword.control.jasm</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(true|false|nil)\b</string>
					<key>name</key>
					<string>constant.language.jasm</string>
				</dict>
			</array>
		</dict>
		<key>line_comment</key>
		<dict>
			<key>begin</key>
			<string>;</string>
			<key>comment</key>
			<string>Single-line comment</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<key>numerics</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.jasm</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b([0-9]+(\.[0-9]+)?)(_sz)?\b</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.jasm</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\u\{[0-9A-Fa-f]{4}\}</string>
							<key>name</key>
							<string>constant.character.escape.jasm</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\x([0-9A-Fa-f]{2})</string>
							<key>name</key>
							<string>constant.character.escape.jasm</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\[0-9a-zA-Z]</string>
							<key>name</key>
							<string>constant.character.escape.jasm</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.jasm</string>
</dict>
</plist>
