<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>$schema</key>
	<string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
	<key>name</key>
	<string>June</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numerics</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#identifiers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#line_comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#block_comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block_comment</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>comment</key>
			<string>Multi-line comment</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block_comment</string>
				</dict>
			</array>
		</dict>
		<key>identifiers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.june</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?=[\s\.]*)\b(((?!func))([a-zA-Z_][a-zA-Z0-9_]*))[\s]*(?=\()</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.struct.june</string>
						</dict>
					</dict>
					<key>match</key>
					<string>struct[\s]*([a-zA-Z_][a-zA-Z0-9_]*)[\s]*{</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(r#)?\b(let|return|if|else|for|in|continue|break|fn|struct|as|impl|public|typeof|import)\b</string>
					<key>name</key>
					<string>keyword.control.june</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(true|false|nil)\b</string>
					<key>name</key>
					<string>constant.language.june</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(r#)?\b(self)\b</string>
					<key>name</key>
					<string>constant.other.june</string>
				</dict>
			</array>
		</dict>
		<key>line_comment</key>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>comment</key>
			<string>Single-line comment</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<key>numerics</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.june</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b([0-9]+(\.[0-9]+)?)\b</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\+=?|-=?|\/=?|\*=?|&gt;&gt;=?|&lt;&lt;=?|&lt;=?|&gt;=?|==?|%=?|\|(\|)?|&amp;&amp;?|!=?)</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.june</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.june</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\u\{[0-9A-Fa-f]{4}\}</string>
							<key>name</key>
							<string>constant.character.escape.june</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\x([0-9A-Fa-f]{2})</string>
							<key>name</key>
							<string>constant.character.escape.june</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\[0-9a-zA-Z]</string>
							<key>name</key>
							<string>constant.character.escape.june</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>#{</string>
							<key>end</key>
							<string>}</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\\u\{[0-9A-Fa-f]{4}\}</string>
									<key>name</key>
									<string>constant.character.escape.june</string>
								</dict>
								<dict>
									<key>match</key>
									<string>\\x([0-9A-Fa-f]{2})</string>
									<key>name</key>
									<string>constant.character.escape.june</string>
								</dict>
								<dict>
									<key>match</key>
									<string>\\[0-9a-zA-Z]</string>
									<key>name</key>
									<string>constant.character.escape.june</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>match</key>
					<string>'([^'\s]+)'</string>
					<key>name</key>
					<string>string.quoted.single.june</string>
				</dict>
			</array>
		</dict>
		<key>types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b[A-Z_][A-Z0-9_]*\b</string>
					<key>name</key>
					<string>constant.other.caps.june</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[A-Z_][a-zA-Z0-9_]*\b</string>
					<key>name</key>
					<string>entity.name.class.june</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(int|float|string|bool)\b</string>
					<key>name</key>
					<string>entity.name.type.june</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.june</string>
</dict>
</plist>
